jobs:
  expo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4          # Node 18 for Expo 49+
        with:
          node-version: 18
          cache: 'npm'

      - uses: expo/expo-github-action@v8
        with:
          expo-version: latest              # <-- fixed
          expo-cache: true
          packager: true
